force-app/main/default/objects/Checkout_Payment_Config__c/Checkout_Payment_Config__c.object-meta.xml
<CustomObject>
    <label>Checkout_Payment_Config</label>
    <nameField>
        <label>Checkout_Payment_Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checkout_Payment_Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checkout_Payment_Config__c/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <label>Secret Key</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Klarna_Setting__mdt/Klarna_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Klarna Setting</label>
    <pluralLabel>Klarna Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Klarna_Setting__mdt/fields/Description_Details__c.field-meta.xml
<CustomField>
    <fullName>Description_Details__c</fullName>
    <defaultValue>(&quot;Your order with Checkout.com&quot;)</defaultValue>
    <inlineHelpText
  >This text will be included in description field from klarna object for the capture Klarna payment.</inlineHelpText>
    <label>Description Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Klarna_Setting__mdt/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <inlineHelpText
  >By default the environment will be set to Sandbox, If you want to use Klarna in production, please make sure to set it as Production.</inlineHelpText>
    <label>Environment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sandbox</fullName>
                <default>true</default>
                <label>Sandbox</label>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Klarna_Setting__mdt/fields/Include_Description__c.field-meta.xml
<CustomField>
    <fullName>Include_Description__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Include Description</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Klarna_Setting__mdt/fields/Include_Products__c.field-meta.xml
<CustomField>
    <fullName>Include_Products__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText
  >If checked, the products related to the order summary corresponding to the payment will be included.</inlineHelpText>
    <label>Include Products</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Klarna_Setting__mdt/fields/Include_Shipping_Delay__c.field-meta.xml
<CustomField>
    <fullName>Include_Shipping_Delay__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include Shipping Delay</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Klarna_Setting__mdt/fields/Include_Shipping_Info__c.field-meta.xml
<CustomField>
    <fullName>Include_Shipping_Info__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText
  >If checked, the shipments related to the order summary corresponding to the payment will be included.</inlineHelpText>
    <label>Include Shipping Info</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Klarna_Setting__mdt/fields/Shipping_Delay_Value__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Delay_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText
  >If you want to submit a value greater than 0, this needs to be enabled in your account.</inlineHelpText>
    <label>Shipping Delay Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CheckoutPaymentConfigQuery.cls
/**
 * @description       : queries for Checkout Payment Config
 * @author            : roberto.ehlert@osf.digital
 * @group             :
 * @last modified on  : 03-22-2021
 * @last modified by  : rafael.nascimento@osf.digital
 * Modifications Log
 * Ver   Date         Author                       Modification
 * 1.0   03-10-2021   roberto.ehlert@osf.digital   Initial Version
 **/

public with sharing class CheckoutPaymentConfigQuery {
  /**
   * @description Get secret key for the correponding active Checkout Payment Config
   * @author roberto.ehlert@osf.digital | 09-03-2021
   * @return String secret key
   **/
  public static String getSecretKey() {
    List<Checkout_Payment_Config__c> activeConfigs = Utils.validateFieldSecurity(
        Checkout_Payment_Config__c.class.getName(),
        new List<String>{ 'Secret_Key__c' },
        Constants.IS_ACCESSIBLE
      )
      ? [
          SELECT Secret_Key__c
          FROM Checkout_Payment_Config__c
          WHERE Active__c = TRUE
          LIMIT 1
        ]
      : null;

    return !activeConfigs.isEmpty() ? activeConfigs[0].Secret_Key__c : null;
  }

  /**
   * @description Get Klarna Settings
   * @author ana-maria.levinta@osf.digital | 05-20-2021
   * @return Klarna_Setting__mdt the settings for the Klarna payment
   **/
  public static Klarna_Setting__mdt getKlarnaSettings() {
    return Utils.validateFieldSecurity(
        Klarna_Setting__mdt.class.getName(),
        new List<String>{
          'Description_Details__c',
          'Environment__c',
          'Include_Description__c',
          'Include_Products__c',
          'Include_Shipping_Delay__c',
          'Include_Shipping_Info__c',
          'Shipping_Delay_Value__c'
        },
        Constants.IS_ACCESSIBLE
      )
      ? [
          SELECT
            Description_Details__c,
            Environment__c,
            Include_Description__c,
            Include_Products__c,
            Include_Shipping_Delay__c,
            Include_Shipping_Info__c,
            Shipping_Delay_Value__c
          FROM Klarna_Setting__mdt
          WHERE Label = 'Default'
          LIMIT 1
        ]
      : null;
  }
}