force-app/main/default/objects/Checkout_Payment_Config__c/Checkout_Payment_Config__c.object-meta.xml
<CustomObject>
    <label>Checkout_Payment_Config</label>
    <nameField>
        <label>Checkout_Payment_Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checkout_Payment_Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checkout_Payment_Config__c/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <label>Secret Key</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Checkout_Payment_Config__c/fields/Webhook_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Webhook_Endpoint__c</fullName>
    <label>Webhook Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Webhook_Event_Types__mdt/Webhook_Event_Types__mdt.object-meta.xml
<CustomObject>
    <label>Webhook Event Types</label>
    <pluralLabel>Webhook Event Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/Webhook_Event_Types__mdt/fields/Checkout_Name__c.field-meta.xml
<CustomField>
    <fullName>Checkout_Name__c</fullName>
    <label>Checkout Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webhook_Event_Types__mdt/fields/Subscribed__c.field-meta.xml
<CustomField>
    <fullName>Subscribed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subscribed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/WebhooksVerification_Queueable.cls
/**
 * @description       : Make the subscription of the webhooks at Chekout Api
 * @author            : roberto.ehlert@osf.digital
 * @group             :
 * @last modified on  : 03-24-2021
 * @last modified by  : rafael.nascimento@osf.digital
 * Modifications Log
 * Ver   Date         Author                       Modification
 * 1.0   03-09-2021   rafael.nascimento@osf.digital   Initial Version
 **/
public with sharing class WebhooksVerification_Queueable implements Queueable, Database.AllowsCallouts {
  private List<Checkout_Payment_Config__c> configs;

  public WebhooksVerification_Queueable(
    List<Checkout_Payment_Config__c> configs
  ) {
    this.configs = configs;
  }

  public void execute(QueueableContext context) {
    List<Webhook_Event_Types__mdt> eventTypes = Utils.validateFieldSecurity(
        Webhook_Event_Types__mdt.class.getName(),
        new List<String>{ 'Checkout_Name__c' },
        Constants.IS_ACCESSIBLE
      )
      ? [
          SELECT Checkout_Name__c
          FROM Webhook_Event_Types__mdt
          WHERE Subscribed__c = TRUE
        ]
      : null;

    List<SalesforceValidationException> exceptions = new List<SalesforceValidationException>();

    for (Checkout_Payment_Config__c config : configs) {
      SalesforceValidationException ex = upsertWebHooks(eventTypes, config);
      if (ex != null) {
        exceptions.add(ex);
      }
    }

    if (!exceptions.isEmpty()) {
      new CustomException().log(exceptions);
    }
  }

  /**
   * @description get the event types active on the webhooks at checkout api
   * @author rafael.nascimento@osf.digital | 03-12-2021
   * @param config the active Checkout_Payment_Config__c
   * @return A set of the event types name
   **/

  private WebhooksWrapper getOnlineWebhook(Checkout_Payment_Config__c config) {
    HttpRequest request = new WebhooksGetRequest(config.Secret_Key__c)
      .getRequest();
    HttpResponse response = new http().send(request);

    if (response.getStatusCode() == 200) {
      for (
        WebhooksWrapper webhooks : ((List<WebhooksWrapper>) JSON.deserialize(
          response.getBody(),
          List<WebhooksWrapper>.class
        ))
      ) {
        if (webhooks.url == config.Webhook_Endpoint__c) {
          return webhooks;
        }
      }
    }

    return null;
  }

  /**
   * @description update or insert the active event types
   * @author rafael.nascimento@osf.digital | 03-12-2021
   * @param eventTypes list of the active event types at the org
   * @param config the active Checkout_Payment_Config__c
   * @return A set of the event types name
   **/
  private SalesforceValidationException upsertWebHooks(
    List<Webhook_Event_Types__mdt> eventTypes,
    Checkout_Payment_Config__c config
  ) {
    List<String> eventsToPost = new List<String>();
    WebhooksWrapper webhook = getOnlineWebhook(config);
    HttpRequest request;

    for (Webhook_Event_Types__mdt eventType : eventTypes) {
      eventsToPost.add(eventType.Checkout_Name__c);
    }

    if (webhook != null) {
      webhook.event_types = eventsToPost;
      request = new WebhooksPatchRequest(webhook, config).getRequest();
    } else {
      request = new WebhooksPostRequest(eventsToPost, config).getRequest();
    }

    HttpResponse response = new http().send(request);

    if (response.getStatusCode() < 200 || response.getStatusCode() > 299) {
      return new SalesforceValidationException(
        'Request not successful: StatusCode: ' +
        response.getStatusCode() +
        ' Status:' +
        +response.getStatus()
      );
    }

    return null;
  }
}